version: '3.4'
services:
  database:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: hasstudio
      MYSQL_ROOT_PASSWORD: admin@123
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin@123
    ports:
      - "3307:3306"
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8088:80
    environment:
      - PMA_ARBITRARY=1